-- COLA Agent Platform - Initial Database Schema
-- Version 1.0.0

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Users table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    enabled BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    last_login TIMESTAMP
);

CREATE INDEX idx_user_email ON users(email);
CREATE INDEX idx_user_username ON users(username);

-- User roles table
CREATE TABLE user_roles (
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, role)
);

-- Projects table
CREATE TABLE projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    description TEXT,
    language VARCHAR(50),
    framework VARCHAR(100),
    status VARCHAR(20) NOT NULL DEFAULT 'PLANNING',
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT chk_project_status CHECK (status IN ('PLANNING', 'CODING', 'TESTING', 'DEPLOYING', 'COMPLETED', 'FAILED'))
);

CREATE INDEX idx_project_user ON projects(user_id);
CREATE INDEX idx_project_status ON projects(status);
CREATE INDEX idx_project_created_at ON projects(created_at DESC);

-- Conversations table
CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    message TEXT NOT NULL,
    role VARCHAR(20) NOT NULL,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    metadata JSONB,
    CONSTRAINT chk_conversation_role CHECK (role IN ('USER', 'ASSISTANT', 'SYSTEM'))
);

CREATE INDEX idx_conversation_project ON conversations(project_id);
CREATE INDEX idx_conversation_timestamp ON conversations(timestamp);

-- Generated files table
CREATE TABLE generated_files (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    file_path VARCHAR(500) NOT NULL,
    content TEXT NOT NULL,
    language VARCHAR(50),
    version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_file_project ON generated_files(project_id);
CREATE INDEX idx_file_path ON generated_files(file_path);
CREATE UNIQUE INDEX idx_file_project_path ON generated_files(project_id, file_path);

-- Build logs table
CREATE TABLE build_logs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    build_type VARCHAR(50),
    status VARCHAR(20) NOT NULL,
    logs TEXT,
    duration_ms BIGINT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_build_status CHECK (status IN ('SUCCESS', 'FAILURE', 'IN_PROGRESS'))
);

CREATE INDEX idx_build_project ON build_logs(project_id);
CREATE INDEX idx_build_timestamp ON build_logs(timestamp DESC);

-- Deployments table
CREATE TABLE deployments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    project_id UUID NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    container_id VARCHAR(255),
    image_name VARCHAR(255),
    status VARCHAR(20) NOT NULL DEFAULT 'DEPLOYING',
    deployed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    port INTEGER,
    endpoint_url VARCHAR(500),
    CONSTRAINT chk_deployment_status CHECK (status IN ('DEPLOYING', 'RUNNING', 'STOPPED', 'FAILED'))
);

CREATE INDEX idx_deployment_project ON deployments(project_id);
CREATE INDEX idx_deployment_container ON deployments(container_id);
CREATE INDEX idx_deployment_status ON deployments(status);

-- Insert default admin user (password: admin123 - should be changed in production)
-- Password is bcrypt hash of 'admin123'
INSERT INTO users (id, username, email, password, first_name, last_name, enabled)
VALUES (
    uuid_generate_v4(),
    'admin',
    'admin@cola-agent.com',
    '$2a$10$dXJ3SW6G7P50lGmMkkmwe.20cQQubK3.HZWzG3YB1tlRy.fqvM/BG',
    'Admin',
    'User',
    true
);

-- Insert admin role
INSERT INTO user_roles (user_id, role)
SELECT id, 'ROLE_ADMIN' FROM users WHERE username = 'admin';

-- Comments
COMMENT ON TABLE users IS 'Application users with authentication credentials';
COMMENT ON TABLE projects IS 'Coding projects managed by the AI agent';
COMMENT ON TABLE conversations IS 'Chat history between users and the AI agent';
COMMENT ON TABLE generated_files IS 'Files generated by the AI agent for projects';
COMMENT ON TABLE build_logs IS 'Compilation and build execution logs';
COMMENT ON TABLE deployments IS 'Deployed applications and containers';
