package com.cola.agent.dto;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

/**
 * Response for code completion.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CompletionResponse {

    // The completion text
    private String completion;

    // Alternative completions (if requested)
    private List<String> alternatives;

    // Confidence score (0.0 to 1.0)
    private double confidence;

    // Whether this is a multi-line completion
    private boolean multiLine;

    // Source of completion (cache, model, etc.)
    private CompletionSource source;

    // Latency in milliseconds
    private long latencyMs;

    // Tokens used
    private int tokensUsed;

    public enum CompletionSource {
        CACHE,          // Retrieved from cache
        MODEL,          // Generated by AI model
        HYBRID,         // Combination of cache and model
        FALLBACK        // Fallback completion
    }

    /**
     * Create a completion from cache.
     */
    public static CompletionResponse fromCache(String completion, long latencyMs) {
        return CompletionResponse.builder()
            .completion(completion)
            .source(CompletionSource.CACHE)
            .confidence(0.95)
            .latencyMs(latencyMs)
            .build();
    }

    /**
     * Create a completion from model.
     */
    public static CompletionResponse fromModel(String completion, long latencyMs, int tokens) {
        return CompletionResponse.builder()
            .completion(completion)
            .source(CompletionSource.MODEL)
            .confidence(0.85)
            .latencyMs(latencyMs)
            .tokensUsed(tokens)
            .build();
    }
}
